logging:
  level:
    org.springframework.security: DEBUG
security:
  sessions: ALWAYS
spring:
  session:
    store-type: redis
zuul:
  routes:
    ui:
      url: http://ui.my-project-2.scv:8080
      sensitive-headers:
    admin:
      url: http://admin.my-project-2.scv:8080
      sensitive-headers:
    resource:
      url: http://resource.my-project-2.scv:8080
      sensitive-headers:

spring:
  redis:
    host: http://redis.my-project-2.svc:6379