logging:
  level:
    org.springframework.security: DEBUG

security:
  sessions: ALWAYS

spring:
  session:
    store-type: mongo
  data:
    mongodb:
      host: http://mongodb.my-project-2.svc

zuul:
  routes:
    ui:
      url: http://ui.my-project-2.svc:8080
      sensitive-headers:
    admin:
      url: http://admin.my-project-2.svc:8080
      sensitive-headers:
    resource:
      url: http://resource.my-project-2.svc:8080
      sensitive-headers:
