logging:
  level:
    org.springframework.security:

security:
  sessions: ALWAYS

spring:
  session:
    store-type: redis
  redis:
      host: http://redis.my-project-2.svc:6379

zuul:
  routes:
    ui:
      url: http://ui.my-project-2.scv:8080
      sensitive-headers:
    admin:
      url: http://admin.my-project-2.scv:8080
      sensitive-headers:
    resource:
      url: http://resource.my-project-2.scv:8080
      sensitive-headers:
